### ISSUE TITLE
All posts show "ENCONTRADO" status in "Ver Publicación" text even if they haven't been found

### ISSUE THREAD

**Issue by DanielSolis00209020** [SIG-ACA-PP/Fido-Finder-App#14]
All posts on the app are incorrectly displaying the status 'ENCONTRADO' in the "Ver Publicación" text, regardless of whether the pet has actually been found or not.

**Steps to reproduce:**
1. Go to the feed on FidoFinder application.
2. View whatever post.
3. View the post details.
4. Notice that the "Ver Publicación" text shows the status 'ENCONTRADO' even though the pet is still lost.

**Expected behavior:**
The "Ver Publicación" text should accurately reflect the current status of the pet (e.g., 'PERDIDA' if the pet hasn't been found, 'ENCONTRADO' if the pet has been found).

**Additional information:**
The issue seems to be related to the logic that sets the status text in the post details view.
This issue affects all users of the application who view or create posts.

**Suggested solution:**
Investigate the logic responsible for setting the status text in the post details view and ensure that it accurately reflects the actual status of the pet.

**Comment by rivasdiego-dev** [comment]
Fixed in commit d5cf231e58861aadc43e3c1c5cb03373cc5b958a 👍
