### ISSUE TITLE
Contact owner button is not working

### ISSUE THREAD

**Issue by carlosxmerca** [SIG-ACA-PP/Fido-Finder-App#7]
The "Contact Owner" button is not functioning as expected. When users attempt to contact the owner via this button, nothing happens. This issue is critical as it hinders communication between users and pet owners. Below are the details and steps to reproduce the issue:

**Comment by rivasdiego-dev** [comment]
Resolved issue in 72d4e811e73cb1783c84f1841f99419329810c81.

In the commit, implemented User page to be able to see the user's contact information. Also, corrected several view and logical issues.
